---
kind: pipeline
type: ssh
name: Deploy

server:
  host:
    from_secret: HOST_ADDR
  user:
    from_secret: USER
  password:
    from_secret: PASSWORD

steps:
- name: Deploy via docker
  environment:
    DRONE_REPO_SECRET:
      from_secret: DRONE_REPO_SECRET
    ALEXANDRE:
      from_secret: ALEXANDRE
    DRONE_FILE_VAR: "This is my drone file env var."
  commands:
    - echo DRONE_REPO_SECRET=$DRONE_REPO_SECRET >> .env
    - echo ALEXANDRE=$ALEXANDRE >> .env
    - echo $ALEXANDRE
    - sudo docker-compose -f docker-compose.yml -f docker-compose.prod.yml up -d --build --force-recreate